version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_DATABASE: ${DATABASE_NAME}
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql

  app:
    build: .
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    volumes:
      - log_volume:/app/logs
      # - ./src:/app/src # restart server if file change happens in src directory
volumes:
  db_volume:
  log_volume:
